### ISSUE TITLE
The default folder of container is changed

### ISSUE THREAD

**Issue by yangdingyu** [intel/platform-resource-manager#3]
Hi, 
I have one problem that the default file fold of container is changed in my docker.
The fold is "/sys/fs/cgroup/perf_event/system.slice/docker-' + cid + '.scope/"
However, the script of eris is setting the fold as '/sys/fs/cgroup/perf_event/docker/'

Althrough I changed the script at line 300: 
f key in ctx.lc_set:
            cgps.append('/sys/fs/cgroup/perf_event/system.slice/docker-' + cid + '.scope/')

There still exists some errors as :
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "eris.py", line 362, in monitor
    func(ctx)
  File "eris.py", line 351, in mon_metric_cycle
    set_metrics(ctx, data)
  File "eris.py", line 85, in set_metrics
    container = ctx.metric_cons[cid]
KeyError: 'docker-8348628c9f821235b83d46b4d6a36d36796dd86a3f1bf23d7560d6935041f416.scope'

The docker version is:  Docker version 1.13.1, build 8633870/1.13.1 ,
and the kernel version is : 4.9.93

Thanks.

**Comment by thuang6** [comment]
#5 fixed the issue @yangdingyu
