### ISSUE TITLE
how can i configure the variable PERF_ATTR_SIZE_VER5 when i make the libpgos.so?

### ISSUE THREAD

**Issue by xiaoyuzhoua** [intel/platform-resource-manager#40]
when i make the libpgos.so, there is an error "./perf.go:26:37: error: 'PERF_ATTR_SIZE_VER5' undeclared here (not in a function)
 // uint32_t def_PERF_ATTR_SIZE_VER5 = PERF_ATTR_SIZE_VER5; "
Can i know what the variable "PERF_ATTR_SIZE_VER5" means and how can i initial it?

**Comment by WangJialei-A** [comment]
@xiaoyuzhoua 
The variable is a marco defined in linux header.
https://github.com/torvalds/linux/blob/afe6fe7036c6efdcb46cabc64bec9b6e4a005210/include/uapi/linux/perf_event.h#L302

Could you check your /usr/include/linux/perf_event.h on your building machine?

**Comment by xiaoyuzhoua** [comment]
Yes,i got the value 112.Thanks for your answer
