### ISSUE TITLE
The resctrl file system doesn't exits in my kernel (3.10),but the "llcoccup.py" opens  "/sys/fs/resctrl/info/L3/cbm_mask", need i update my kernel or just use the pqos can work?

### ISSUE THREAD

**Issue by xiaoyuzhoua** [intel/platform-resource-manager#41]
The resctrl file system doesn't exits in my kernel (3.10),but the "llcoccup.py" opens  "/sys/fs/resctrl/info/L3/cbm_mask", need i update my kernel or just use the pqos can work?

**Comment by WangJialei-A** [comment]
@xiaoyuzhoua 
Please run 'cat /proc/filesystems | grep resctrl'
Update the kernel if nothing returned.

**Comment by xiaoyuzhoua** [comment]
Nothing returned.
