### ISSUE TITLE
eris pgos core dumped 

### ISSUE THREAD

**Issue by thuang6** [intel/platform-resource-manager#49]
panic: runtime error: index out of range

goroutine 17 [running, locked to thread]:
main.(*Cgroup).GetPgosHandler(0xc0003e2150, 0x0)
        /home/dcm/thuang6/platform-resource-manager/pgos/main.go:239 +0x2a2
main.collect(0x2800000000, 0x100004844, 0x0, 0x7f5a9056bdf0, 0x0, 0x0, 0x0, 0x0)
        /home/dcm/thuang6/platform-resource-manager/pgos/main.go:132 +0x270
main._cgoexpwrap_7acf3ebd5668_collect(0x2800000000, 0x100004844, 0x0, 0x7f5a9056bdf0, 0x0, 0x0, 0x0, 0x0)
        _cgo_gotypes.go:327 +0x71
Aborted (core dumped)

**Comment by thuang6** [comment]
@WangJialei-A

**Comment by WangJialei-A** [comment]
Should be already fixed in this [PR](https://github.com/intel/platform-resource-manager/pull/47)
